telegram:
  bot_token: "token"
  admin_ids: [1,2,3,4]
  bot_username: "your_bot_username"

postgres:
  host: "localhost"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  db: "template_app"
  # pool_size: 30
  # pool_timeout: 30
  # pool_recycle: 3600
  # max_overflow: 20
  # pool_pre_ping: true
  # echo_pool: false

auth:
  secret_key: "2b8f131dfcf30c00ba5b28676dac2dcddd7c4a75637f03a4b2e57ca95810dbcc"  # openssl rand -hex 32
  algorithm: "HS256"
  access_token_expire_minutes: 30

telemetry:
  alloy_base: "http://localhost:4318"
  export_metrics: true  # for prod set to true, for dev and test set to false
  export_traces: true  # for prod set to true, for dev and test set to false
  sentry_dsn: null
  sentry_environment: "development"
  sentry_release: null
  sentry_traces_sample_rate: 1.0
